name: Test site1
favicon: null
layout_spectrum: 0.47514
typography_spectrum: 0.65631
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#5d83c4'
    - '#090c11'
    - '#373737'
    - '#ffffe3'
    - '#f3b086'
  brandStrength: 0
  lightness: 0.375
  saturation: 0.125
  rhythmicContrast: 1
purpose: []
