name: Test site1
favicon: null
layout_spectrum: 0.73951
typography_spectrum: 0.65631
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#090714'
    - '#fcfefd'
    - '#e8b252'
    - '#d38200'
    - '#3e4420'
  brandStrength: 0.9391097880434245
  lightness: 0.375
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose: []
